location = "/Users/kobas-mac/Library/Application Support/Code/User/snippets/comp-prog.json.code-snippets"

[[rust.entries]]
prefix = "getline"
filename = "vscode/getline.rs"

[[rust.entries]]
prefix = "ints"
filename = "vscode/ints.rs"
has_parameters = true

[[rust.entries]]
prefix = "parse"
filename = "vscode/parse.rs"
has_parameters = true

[[rust.entries]]
prefix = "digitsum"
filename = "vscode/digitsum.rs"

[[rust.entries]]
prefix = "count_matching_with_size"
filename = "vscode/count_matching_with_size.rs"

[[rust.entries]]
prefix = "quot"
filename = "vscode/quot.rs"

[[rust.entries]]
prefix = "comb"
filename = "vscode/comb.rs"

[[rust.entries]]
prefix = "neg_comb"
filename = "vscode/neg_comb.rs"

[[rust.entries]]
prefix = "inv"
filename = "vscode/inv.rs"
has_parameters = true

[[rust.entries]]
prefix = "bs"
filename = "binary_search.rs"

[[rust.entries]]
prefix = "mint"
filename = "MInt.rs"

[[rust.entries]]
prefix = "next_permutation"
filename = "next_permutation.rs"

[[rust.entries]]
prefix = "floor_sum"
filename = "floor_sum.rs"

[[rust.entries]]
prefix = "fact"
filename = "fact_init.rs"
depends_on = ["MInt.rs"]

[[rust.entries]]
prefix = "2sat"
filename = "two_sat.rs"

[[rust.entries]]
prefix = "perm"
filename = "perm.rs"

[[rust.entries]]
prefix = "subsets"
filename = "subsets.rs"

[[rust.entries]]
prefix = "rng"
filename = "rng.rs"

[[rust.entries]]
prefix = "uf"
filename = "graph/UnionFind.rs"

[[rust.entries]]
prefix = "dijk"
filename = "graph/Dijkstra.rs"

[[rust.entries]]
prefix = "scc"
filename = "graph/SCC.rs"

[[rust.entries]]
prefix = "dinic"
filename = "graph/Dinic.rs"

[[rust.entries]]
prefix = "min-cost-flow"
filename = "graph/MinCostFlow.rs"

[[rust.entries]]
prefix = "min-cost-circ"
filename = "graph/MinCostCirc.rs"
depends_on = ["graph/MinCostFlow.rs"]

[[rust.entries]]
prefix = "submodular-min"
filename = "graph/SubmodMin.rs"
depends_on = ["graph/Dinic.rs"]

[[rust.entries]]
prefix = "segtree"
filename = "datastr/SegTree.rs"

[[rust.entries]]
prefix = "wm"
filename = "datastr/WaveletMatrix.rs"

[[rust.entries]]
prefix = "bitset"
filename = "datastr/BitSet.rs"

[[rust.entries]]
prefix = "cht"
filename = "datastr/MinCHT.rs"

[[rust.entries]]
prefix = "zalgo"
filename = "string/z_algorithm.rs"

[[rust.entries]]
prefix = "suffix"
filename = "string/sa_is.rs"

[[rust.entries]]
prefix = "lcp"
filename = "string/lcp.rs"
depends_on = ["string/sa_is.rs"]

[[cpp.entries]]
prefix = "uf"
filename = "graph/UnionFind.cpp"
